#!/bin/bash

# prepare X11
rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
mkdir -p /etc/X11/xorg.conf.d
cp -rf ./99-calibration.conf  /etc/X11/xorg.conf.d/99-calibration.conf
cp -rf ./99-fbturbo.conf  /etc/X11/xorg.conf.d/99-fbturbo.conf

# load module on boot
cp ./waveshare35a.dtbo /boot/overlays/
# rewrite boot path for Raspberry Pi OS Bookworm
cfgpath="/boot"
if [[ -f /etc/zsh_command_not_found ]]; then
  if [[ "$(cat /boot/config.txt | grep 'DO NOT EDIT THIS FILE' -c)" -eq 1 ]]; then
    cfgpath="/boot/firmware"
  fi
fi
echo "hdmi_force_hotplug=1" >> $cfgpath/config.txt
echo "dtparam=i2c_arm=on" >> $cfgpath/config.txt
echo "dtparam=spi=on" >> $cfgpath/config.txt
echo "enable_uart=1" >> $cfgpath/config.txt
echo "dtoverlay=waveshare35a:rotate=90" >> $cfgpath/config.txt
cp ./cmdline.txt $cfgpath/

# touch screen calibration
apt-get install xserver-xorg-input-evdev
cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf

# done :)
echo "reboot now"
reboot
